name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.9'

      - name: Build
        run: gradle build
      - run: mv build/libs/CodeCracker-0.0.1-SNAPSHOT.jar build/libs/CodeCracker-1.${{ env.build-number }}.1.jar
      - run: mkdir -p staging && cp build/libs/CodeCracker-1.${{ env.build-number }}.1.jar staging/CodeCracker-1.${{ env.build-number }}.1.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "version"
          files: |
            staging/*.jar

